import {describe,it,expect} from 'vitest';
import {createRetrievalModel,gradeModel,selectDailyModels,applyModelEvidence,DAY,settingsFor,priorityScore} from './modelRetrieval.js';
const now=new Date(2026,7,30,12).getTime();
const make=(id='m',extra={})=>createRetrievalModel({id,title:'A model',prompt:'Reconstruct the causal relationships',blockId:'b',...extra},now);
describe('model retrieval scheduling',()=>{
 it('keeps optional Saturday retrieval capped and excludes released models',()=>{const saturday=new Date(2026,8,5,12).getTime();const future={...make(),nextReviewAt:saturday+DAY};expect(selectDailyModels([future],{},saturday,'b').selected).toHaveLength(0);expect(selectDailyModels([future],{weekend:true},saturday,'b').selected).toHaveLength(1);expect(selectDailyModels([{...future,status:'Released'}],{weekend:true},saturday,'b').selected).toHaveLength(0);});
 it('validates creation and sane budgets',()=>{expect(()=>make('m',{prompt:' '})).toThrow();expect(settingsFor({minutes:999,cap:99})).toMatchObject({minutes:10,cap:4});expect(make().nextReviewAt).toBe(now);expect(createRetrievalModel({...make()},now,{sameDay:false}).nextReviewAt).toBe(now+DAY);});
 it('returns broken tomorrow and repeated shaky sooner',()=>{expect(gradeModel(make(),'broken',now,'a')).toMatchObject({status:'Learning',nextReviewAt:now+DAY});const shaky=gradeModel(make(),'shaky',now,'b');expect(shaky.nextReviewAt).toBe(now+3*DAY);expect(gradeModel(shaky,'shaky',now+3*DAY,'c').nextReviewAt).toBe(now+5*DAY);});
 it('spaces solids 7,14,30 days before long-term release',()=>{let m=make();let t=now;for(const [i,days] of [7,14,30].entries()){m=gradeModel(m,'solid',t,String(i));expect(m.nextReviewAt).toBe(t+days*DAY);t=m.nextReviewAt;}m=gradeModel(m,'solid',t,'last');expect(m.status).toBe('Released');expect(m.nextReviewAt).toBe(null);});
 it('does not accelerate release with early successes',()=>{const m=gradeModel(make(),'solid',now,'a');const early=gradeModel(m,'solid',now+DAY,'b');expect(early.solidStreak).toBe(1);expect(early.nextReviewAt).toBe(m.nextReviewAt);expect(gradeModel(early,'solid',now+DAY,'b')).toBe(early);});
 it('handles no models and no due models',()=>{expect(selectDailyModels([],{},now,'b').selected).toEqual([]);expect(selectDailyModels([{...make(),nextReviewAt:now+DAY}],{},now,'b').selected).toEqual([]);});
 it('keeps a large backlog inside both hard limits',()=>{const models=Array.from({length:30},(_,i)=>make(String(i)));expect(selectDailyModels(models,{},now+90*DAY,'b').selected).toHaveLength(3);expect(selectDailyModels(models,{minutes:20,cap:2},now,'b').selected).toHaveLength(2);});
 it('counts today’s reviews across blocks and never reselects a reviewed model',()=>{const done=gradeModel(make('a',{blockId:'other',minutes:5}),'solid',now,'a');const models=[done,make('b',{minutes:5}),make('c')];expect(selectDailyModels(models,{minutes:5},now,'b').selected).toHaveLength(0);expect(selectDailyModels([gradeModel(make(),'broken',now,'a')],{},now,'b').selected).toHaveLength(0);});
 it('skipping days does not accumulate a daily budget',()=>{const models=Array.from({length:20},(_,i)=>make(String(i)));expect(selectDailyModels(models,{minutes:5},now+100*DAY,'b').selected).toHaveLength(1);});
 it('handles absent or imminent exams and manual priority',()=>{expect(Number.isFinite(priorityScore(make(),now,null))).toBe(true);expect(priorityScore(make(),now,new Date(now+DAY).toISOString())).toBeGreaterThan(priorityScore(make(),now,null));const high=make('high',{priority:3});expect(selectDailyModels([make(),high],{cap:1},now,'b').selected[0].id).toBe('high');});
 it('reopens released models only for explicit weakness evidence',()=>{const m={...make(),status:'Released',nextReviewAt:null};const reopened=applyModelEvidence(m,{id:'q',at:now,type:'question-miss'});expect(reopened.status).toBe('Shaky');expect(reopened.nextReviewAt).toBe(now);expect(applyModelEvidence(reopened,{id:'q',at:now,type:'question-miss'})).toBe(reopened);});
 it('respects evidence settings and does not equate facts with full retrieval',()=>{const m=make();expect(applyModelEvidence(m,{id:'a',at:now,type:'anki-again'},{ankiEvidence:false})).toBe(m);const next=applyModelEvidence(m,{id:'a',at:now,type:'question-success'});expect(next.history).toEqual([]);expect(next.nextReviewAt).toBe(m.nextReviewAt);expect(priorityScore(next,now)).toBeLessThan(priorityScore(m,now));});
});
